### PR TITLE
 XI Language Support

### PR DESCRIPTION
**Pull request by ppav**
Hello Mark!
I added support "Xi" format. Is a markdown-like language 

[link to Marketplace](https://marketplace.visualstudio.com/items?itemName=grigoryvp.language-xi)

### CODE REVIEW

**Comment by mskelton** [comment]
Thanks for the pull request, but I am a bit hesitant about adding this in as I would like to get away from customizing each language in a very different way from each other.  What does XI look with one dark pro without the changes you made?

**Comment by ppav** [comment]
Of course❗️

You can compare themes and [original](https://github.com/grigoryvp/color-theme/tree/master/vscode) from the @grigoryvp.

**Comment by ppav** [comment]
These changes are made to the main [repository](https://github.com/Binaryify/OneDark-Pro/pull/308)

**Comment by mskelton** [comment]
Thanks for the screenshots.  I'll be happy to merge this in, but I'm also not too keen about using the error color for normal text.  I want to keep that reserved for errors if possible.  Could that be changed to another color?

**Comment by ppav** [comment]
Oh, I do not think 🤔  This will require a few changes, and I want to keep intimacy with the original

**Comment by mskelton** [comment]
I can understand wanting to keep it similar to the original, but I really don't like the idea of using the error color for non-errored text.

**Comment by ppav** [comment]
ok, i'll do it, but it will turn out from [repository](https://github.com/Binaryify/OneDark-Pro)

**Pull request closed without merging**
